networks:
  pesapalm-net:
    external: true

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "30086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pesapalm-net

  pesapalm-api:
    image: gidyon/pesapalm-api:latest
    restart: always
    volumes:
      - ./app.env:/app/.env
      - ./cabin.conf:/app/cabin.conf
    networks:
      - pesapalm-net

  pesapalm-portal:
    image: gidyon/pesapalm-portal:latest
    restart: always
    networks:
      - pesapalm-net
