networks:
  pesapalm-net:
    external: true
  kong-network:
    external: true

services:
  nginx:
    image: nginx:stable
    container_name: nginx_pesapalm
    restart: always
    ports:
      - "30086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pesapalm-net
      - kong-network

  pesapalm-api:
    image: gidyon/pesapalm-api:latest
    command:
      ["--config-file", "/root/app.env", "--casbin-conf", "/root/cabin.conf"]
    restart: always
    volumes:
      - ./app.env:/root/app.env
      - ./cabin.conf:/root/cabin.conf
    networks:
      - pesapalm-net

  pesapalm-portal:
    image: gidyon/pesapalm-portal:latest
    restart: always
    networks:
      - pesapalm-net
