version: "3"

services:
  mysql:
    image: mysql:8.0.18
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/gideon/mysql-storage/bisou/:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: hakty11
      MYSQL_ROOT_PASSWORD: hakty11
      MYSQL_DATABASE: bisou

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  redisgui:
    container_name: redisgui
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
